import { Manrope } from 'next/font/google'
import Header from "./Components/Header/Header"
import Footer from "./Components/Footer"
import './globals.css'

export const metadata = {
  title: 'Audiophile',
  description: 'Generated by create next app',
}

const manrope = Manrope({
  subsets: ['latin'],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
