import { Manrope } from 'next/font/google'
import Header from "./Components/Header/Header"
import Footer from "./Components/Footer"
import { GlobalContextProvider } from "./Context/store"
import { SkeletonTheme } from "react-loading-skeleton"
import "react-loading-skeleton/dist/skeleton.css";
import './globals.css'


export const metadata = {
  title: 'Audiophile',
  description: 'Generated by create next app',
}

const manrope = Manrope({
  subsets: ['latin'],
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SkeletonTheme baseColor="#c2bdbd" highlightColor="#444">
      <html lang="en">
        <body className={manrope.className}>
          <GlobalContextProvider>
            <Header />
            {children}
            <Footer />
          </GlobalContextProvider>
        </body>
      </html>
    </SkeletonTheme>
  )
}
